Repository SoPra-Team-17/Server, pull requests merged in 2020-05, with the labels that each got.

#33 CI + Sonar
  .github/workflows/CI.yml
  .github/workflows/compile.yml
  .github/workflows/static-analysis.yml
  sonar-project.properties
Labels: infrastructure

#66 fixed issue of offering too many gadgets
  src/game/ChoiceHandling.hpp
Labels: bug

#75 added random configs from editor
  exampleConfig/characters.json
  exampleConfig/matchconfig.json
  exampleConfig/matchconfig.match
  exampleConfig/scenario.json
  exampleConfig/scenario.scenario
Labels: prio:--
